force-app/main/default/objects/e_Invois_API__c/e_Invois_API__c.object-meta.xml
<CustomObject>
    <label>e Invois</label>
    <nameField>
        <label>e Invois  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>e Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Spaceship_Name__c/Spaceship_Name__c.object-meta.xml
<CustomObject>
    <description>Spaceship description</description>
    <label>Spaceship</label>
    <nameField>
        <label>Spaceship_Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaceship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Spaceship_Name__c/fields/Crew_Size__c.field-meta.xml
<CustomField>
    <fullName>Crew_Size__c</fullName>
    <description>Crew Size Description</description>
    <inlineHelpText>Crew Size Help</inlineHelpText>
    <label>Crew Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ShipSize__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SpaceshipCrew</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestHighlightForAutomation_4.cls
public class TestHighlightForAutomation_4 {    

    public Integer recordtypeClass(Integer a) {
        
        List<e_Invois_API__c> inv = [Select Id FROM e_Invois_API__c Where RecordTypeId = '0120R000000Uzgx' LIMIT 1 ];
        Integer ans = a;
        return ans;
    }
    public Integer getShipSizeM(Integer a){
    
    Spaceship_Name__c ship = new Spaceship_Name__c();
    boolean shipSize = ship.Crew_Size__c == '< 100';
    Integer b=a;    
    return b;
    }
    
}