force-app/main/default/objects/Cmetadata_API__mdt/Cmetadata_API__mdt.object-meta.xml
<CustomObject>
    <description>for test</description>
    <label>Cmetadata</label>
    <pluralLabel>Cmetadata</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cmetadata_API__mdt/fields/Val1_API__c.field-meta.xml
<CustomField>
    <fullName>Val1_API__c</fullName>
    <label>Val1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cmetadata_API__mdt/fields/Val2_API__c.field-meta.xml
<CustomField>
    <fullName>Val2_API__c</fullName>
    <label>Val2</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/with_lookup__mdt/with_lookup__mdt.object-meta.xml
<CustomObject>
    <description>with loookup in cmt</description>
    <label>with lookup</label>
    <pluralLabel>with lookups</pluralLabel>
</CustomObject>

force-app/main/default/objects/with_lookup__mdt/fields/relation_to_object__c.field-meta.xml
<CustomField>
    <fullName>relation_to_object__c</fullName>
    <description>yes yes relation to object</description>
    <label>relation to object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>with_lookups</relationshipLabel>
    <relationshipName>with_lookups</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/cmtClass.cls
public with sharing class cmtClass {
    public Integer cmtMathode(Integer q) {
        Integer a;
        List<Cmetadata_API__mdt> cmt = [select Val1_API__c from Cmetadata_API__mdt 
                                        ORDER BY DeveloperName DESC LIMIT 1];
        List<with_lookup__mdt> cmtLookup = [SELECT Id, MasterLabel, DeveloperName, Language, NamespacePrefix, Label, 
                                            QualifiedApiName, relation_to_object__c 
                                            FROM with_lookup__mdt where MasterLabel = 'lookup relation'];
        /*
        List<Cmetadata_API__mdt> cmt = [select Val2_API__c from Cmetadata_API__mdt 
                                        ORDER BY DeveloperName DESC LIMIT 1];
        */   
         List<dlrs__LookupRollupSummary2__mdt> manage = [select dlrs__ChildObject__c from dlrs__LookupRollupSummary2__mdt 
                                        ORDER BY DeveloperName DESC LIMIT 1];
        a=q;
        return a;
    }
}