force-app/main/default/objects/Feature_Name__c/Feature_Name__c.object-meta.xml
<CustomObject>
    <label>Feature_Label</label>
    <nameField>
        <label>Feature_Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features_Label</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feature_Name__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>Panaya On Going</description>
    <label>Project_Label</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Description</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Start_API</fullName>
                <label>Start_label1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/updateFeature.cls
public class updateFeature {
    List<Feature_Name__c> Feature=[select id,Name,Project_Name__c from Feature_Name__c];
    List<Feature_Name__c> updateFeature=new List<Feature_Name__c>();
        
    public void doupdate(){
        for(Feature_Name__c obj:Feature)
    	{
            if(obj.Project_Name__c=='Manager')
            {
                obj.Project_Name__c='Description'; 
                updateFeature.add(obj);
            }
        }
    update updateFeature;
    }   
}