force-app/main/default/objects/Bug__c/Bug__c.object-meta.xml
<CustomObject>
    <description>Bug description</description>
    <label>Bug_Label</label>
    <nameField>
        <label>Bug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bugs_Label</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bug__c/fields/Bug_TestedBy_Name__c.field-meta.xml
<CustomField>
    <fullName>Bug_TestedBy_Name__c</fullName>
    <description>Tested By description</description>
    <inlineHelpText>Tested By help</inlineHelpText>
    <label>Tested By Label</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Itay</fullName>
                <default>true</default>
                <label>Itay</label>
            </value>
            <value>
                <fullName>Vlad</fullName>
            </value>
            <value>
                <fullName>Dima</fullName>
            </value>
            <value>
                <fullName>Eyal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/relationship_chaining.cls
public with sharing class relationship_chaining extends extendBug {
@AuraEnabled
    public static Contact getContacts() {
        List<Contact> contacts = 
                [SELECT Account.Owner.LastName FROM Contact limit 1];

        //Add isAccessible() check
        return contacts[0];
    }
    @AuraEnabled
    public static Bug__c getBug() {
        List<Bug__c> Bugs = 
                [SELECT Bug__c.Bug_TestedBy_Name__c FROM Bug__c limit 1];

        //Add isAccessible() check
        return Bugs[0];
    }
    
    extdClass e = extdClass.Open; 
    extdClass e2 = extdClass.Reopen; 
}