force-app/main/default/objects/Bug__c/Bug__c.object-meta.xml
<CustomObject>
    <description>Bug description</description>
    <label>Bug_Label</label>
    <nameField>
        <label>Bug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bugs_Label</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bug__c/fields/Bug_email_Name__c.field-meta.xml
<CustomField>
    <fullName>Bug_email_Name__c</fullName>
    <defaultValue>$Organization.Name</defaultValue>
    <description>Bug email description</description>
    <inlineHelpText>Bug email help</inlineHelpText>
    <label>Bug email Label</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Bug__c/fields/Bug_priority_Name__c.field-meta.xml
<CustomField>
    <fullName>Bug_priority_Name__c</fullName>
    <description>Bug priority description</description>
    <inlineHelpText>Bug priority Help</inlineHelpText>
    <label>Bug priority Label</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Global_BugPriority</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalProcessesTest.cls
@isTest 
public class ApprovalProcessesTest {
	private static testMethod void Test_ApprovalProcesses() { 
        List<Bug__c> bug = new List<Bug__c>{
            new Bug__c(Name='bugtest',Bug_priority_Name__c='Minor',Bug_email_Name__c='test@panaya.com')};  
        String c =  Label.Label_Short_Description;      
        Bug__c b = new Bug__c();
        ApprovalProcesses app = new ApprovalProcesses();
        Integer a = 30;
        System.assertEquals(30, a);
}
}