force-app/main/default/objects/QA_A_API__c/QA_A_API__c.object-meta.xml
<CustomObject>
    <label>QA_A</label>
    <nameField>
        <label>QA_A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QA_A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QA_A_API__c/fields/Dollar_API__c.field-meta.xml
<CustomField>
    <fullName>Dollar_API__c</fullName>
    <formula>$User.CommunityNickname</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dollar</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QA_A_API__c/fields/Status_API__c.field-meta.xml
<CustomField>
    <fullName>Status_API__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active_API</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive_API</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Panding_API</fullName>
                <label>Panding</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QA_B_API__c/QA_B_API__c.object-meta.xml
<CustomObject>
    <label>QA_B</label>
    <nameField>
        <label>QA_B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QA_B</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QA_B_API__c/fields/Description_API__c.field-meta.xml
<CustomField>
    <fullName>Description_API__c</fullName>
    <label>Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QA_B_API__c/fields/Dollar_API__c.field-meta.xml
<CustomField>
    <fullName>Dollar_API__c</fullName>
    <formula>$User.CommunityNickname</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dollar</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QA_B_API__c/fields/QA_A_Lookup_API__c.field-meta.xml
<CustomField>
    <fullName>QA_A_Lookup_API__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QA_A_Lookup</label>
    <referenceTo>QA_A_API__c</referenceTo>
    <relationshipLabel>QA_B</relationshipLabel>
    <relationshipName>QA_B</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QA_B_API__c/fields/Status_API__c.field-meta.xml
<CustomField>
    <fullName>Status_API__c</fullName>
    <label>Status Label</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Global_BugPriority</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/QA_A_TriggerHelper.cls
public class QA_A_TriggerHelper 
{
	public static void createQA_B_record (List<QA_A_API__c> QA_A_List,Map<id,QA_A_API__c> oldMapQA_A)
    {
        List<QA_B_API__c> QA_B_List = new List<QA_B_API__c>();
            for(QA_A_API__c ObjQA_A: QA_A_List)
            {
                if(ObjQA_A.Status_API__c =='Active_API' && oldMapQA_A.get(ObjQA_A.id).Status_API__c =='Inactive_API')
                {
                    QA_B_API__c ObjQA_B = new QA_B_API__c();
                    ObjQA_B.Description_API__c = 'from QA_A_TriggerHelper Class';
                    ObjQA_B.QA_A_Lookup_API__c = ObjQA_A.id;
                    QA_B_List.add(ObjQA_B);
                }
            }
            insert QA_B_List;
    }
    public static void fanc (){
        QA_A_API__c qa = new QA_A_API__c();
        if (qa.Dollar_API__c =='esela'){
            
        }
    }
}