force-app/main/default/objects/QA_A_API__c/QA_A_API__c.object-meta.xml
<CustomObject>
    <label>QA_A</label>
    <nameField>
        <label>QA_A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QA_A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QA_A_API__c/fields/Dollar_API__c.field-meta.xml
<CustomField>
    <fullName>Dollar_API__c</fullName>
    <formula>$User.CommunityNickname</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dollar</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QA_A_API__c/fields/Global_Picklist_API__c.field-meta.xml
<CustomField>
    <fullName>Global_Picklist_API__c</fullName>
    <label>Global Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Global_BugPriority</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/HighlightingIsTest.cls
@isTest
public class HighlightingIsTest {
    static testMethod void Utest()
    {
        HighlightingOfIndirect.fanc();
        QA_A_TriggerHelper.fanc();
        QA_A_API__c QAobj = new QA_A_API__c();
        QAobj.name = 'Unit test';
        if(QAobj.Dollar_API__c == 'esela')
        {
            QAobj.Global_Picklist_API__c = 'Critical';
        }
        insert QAobj;
        
        Test.startTest();
        QAobj.name = 'Unit test1';
        update QAobj;
        Test.stopTest();
        
        List<QA_A_API__c> QAaList = [select name from QA_A_API__c where name = 'Unit test1'];
        system.assertEquals(1,QAaList.size());
    }

}