force-app/main/default/objects/QA_B_API__c/QA_B_API__c.object-meta.xml
<CustomObject>
    <label>QA_B</label>
    <nameField>
        <label>QA_B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QA_B</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QA_B_API__c/fields/Dollar_API__c.field-meta.xml
<CustomField>
    <fullName>Dollar_API__c</fullName>
    <formula>$User.CommunityNickname</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dollar</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestHighlightForAutomation_2.cls
public class TestHighlightForAutomation_2 {
    public Boolean itemInFor(){
        Boolean a = true;
        List<QA_B_API__c> QA_B_List = new List<QA_B_API__c>();
         for(QA_B_API__c item : QA_B_List)
            {
                if(item.Dollar_API__c == 'esela'){
                   Integer i=100;
                   a = false; 
                }            
            }
        return a;
        } 
    
    public Integer staticrelation(Integer a){
        Integer res = a;
        QA_A_TriggerHelper.fanc();
        return res;
    }
    


}